[workspace]
members = [
	"rotmg_packets",
	"rotmg_networking",
]

# don't include debug symbols for dependencies, even in debug mode
# this substantially reduces debug mode binary sizes
[profile.dev.package."*"]
debug = false
