[package]
name = "rotmg_packets"
version = "0.1.0"
authors = ["Dana Marcuse <dana@marcuse.us>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0.18"
serde = { version = "1.0.110", features = [ "derive" ] }
rand = "0.7.3"
