name: Rust checks
on: [push]

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Run clippy (default features)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run clippy (all features)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features
      - name: Run unit tests (default features)
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run unit tests (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --color always
